### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Kumariz0** [Shortink/SOTWayfinder#1]
Saw you starred my Api wrapper and found this gem. If you need help, feel free to tell me. I would love to see more useful FOSS programs for SOT that are not cheats specifically.

**Comment by Shortink** [comment]
Somehow only just seeing this after like 3 weeks lol. Btw do you have discord, i guess i dont get notifications for github

**Comment by Kumariz0** [comment]
All good.
My discord is `Kumariz`
